steps:
  # Langkah untuk build image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-flask-app', '.']

  # Langkah untuk push image ke Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-flask-app']

images:
  - 'gcr.io/$PROJECT_ID/my-flask-app'
