steps:
  # Step to build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/my-flask-app', '.']

  # Step to push the image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/my-flask-app']

images:
  - 'gcr.io/$PROJECT_ID/my-flask-app'

# Optional: Set logging options
options:
  logging: CLOUD_LOGGING_ONLY

# Optional: Specify a timeout for the build (default is 10 minutes)
timeout: '1200s'  # Example: 20 minutes

# Optional: Define substitutions (variables)
substitutions:
  _MY_VARIABLE: 'value'
